version: '2'
services:

  # SQL database
  postgres:
    image: "postgres"
    restart: "always"
    volumes:
      - "ktor-starter-data:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "ktor-starter"
    mem_limit: "1g"

volumes:
  ktor-starter-data: